name: Test workflow
on:
  workflow_dispatch: {}

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y terraform=1.1.9

      - name: Install terragrunt
        run: |
          # With the latest terragrunt, its checking mechanism causes an error,
          # so pin a version
          sudo curl -Lo /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.37.1/terragrunt_linux_amd64
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          timeout-minutes: 15
          limit-access-to-actor: true

      # - uses: actions/checkout@v2

      # - name: Plan
      #   run: |
      #     cd terraform/
      #     terragrunt plan -no-color -input=false
